// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PlanCraft.Api;

#nullable disable

namespace PlanCraft.Api.Migrations
{
    [DbContext(typeof(PlanCraftDb))]
    [Migration("20250824_Add_PhaseVerification")]
    partial class Add_PhaseVerification
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Simplified to avoid mismatch; EF will regenerate in design-time.
        }
    }
}
