// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PlanCraft.Api;

#nullable disable

namespace PlanCraft.Api.Migrations
{
    [DbContext(typeof(PlanCraftDb))]
    [Migration("20250824_3_Add_PhaseAssignment_And_NoAssignedDays")]
    partial class Add_PhaseAssignment_And_NoAssignedDays
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Simplified placeholder; EF tooling will regenerate this in design-time.
        }
    }
}
